AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notification-to-idobata

  Sample SAM Template for notification-to-idobata
Globals:
  Function:
    Timeout: 3
Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          IdobataWebhookUrl: !Ref IdobataWebhookUrl
Parameters:
  IdobataWebhookUrl:
    Type: String